# Generated by Django 5.2.8 on 2025-12-27 22:29

import django_resized.forms
import telegram.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='massage',
            name='pic',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to=telegram.models.message_img),
        ),
    ]
